/** Sub-offices / district offices within SDO Batangas. */
export const SUB_OFFICES: string[] = [
  "AGONCILLO",
  "ALITAGTAG",
  "Balayan East",
  "Balayan West",
  "BALETE",
  "Bauan East",
  "Bauan West",
  "CALATAGAN",
  "CUENCA",
  "IBAAN",
  "LAUREL",
  "LEMERY",
  "LIAN",
  "LOBO",
  "MABINI",
  "MALVAR",
  "MATAASNAKAHOY",
  "NASUGBU EAST",
  "NASUGBU WEST",
  "PADRE GARCIA",
  "ROSARIO EAST",
  "ROSARIO WEST",
  "SAN JOSE",
  "SAN JUAN EAST",
  "SAN JUAN WEST",
  "SAN LUIS",
  "SAN NICOLAS",
  "SAN PASCUAL",
  "SANTA TERESITA",
  "TAAL",
  "TALISAY",
  "TAYSAN",
  "TINGLOY",
  "TUY",
];

/** Mapping of sub-office to its list of schools. */
export const SCHOOLS_BY_SUB_OFFICE: Record<string, string[]> = {
  AGONCILLO: [
    "Bernardo Ondo Memorial Elementary School",
    "Agoncillo Central School",
    "Pamiga Elementary School",
    "Balangon Elementary School",
    "Banyaga Elementary School",
    "Barigon Elementary School",
    "Bilibinwang Elementary School",
    "Coral na Munti Elementary School",
    "Mahabang Gulod Elementary School",
    "Panhulan Elementary School",
    "Pansipit Elementary School",
    "Pook Elementary School",
    "Subic Elementary School",
    "Banyaga National High School",
    "Coral na Munti National High School",
    "Agoncillo National High School",
    "Agoncillo Senior High School",
  ],
  ALITAGTAG: [
    "Alitagtag Central School",
    "Dalipit Elementary School",
    "Munlawin Elementary School",
    "Muzon Elementary School",
    "Pinagkurusan Elementary School",
    "Ping-as Coral Elementary School",
    "Tadlac Elementary School",
    "San Jose T. Reyes Integrated School",
    "Alitagtag National High School",
    "Alitagtag Senior High School",
    "San Jose T. Reyes Integrated School",
  ],
  "Balayan East": [
    "Baclaran Elementary School",
    "Balayan East Central School",
    "Calan Elementary School",
    "Troadio A. Frontera Memorial Elementary School",
    "Dao Elementary School",
    "Don Leon Martinez Memorial Elementary School",
    "Lanatan-Muntingtubig Elementary School",
    "Lucban Elementary School",
    "Patugo Elementary School",
    "Pook Elementary School",
    "Putol Elementary School",
    "Sampaga Elementary School",
    "Juan C. De Lunas Memorial Elementary School",
    "Sucol Elementary School",
    "Balayan National High School",
    "Lucban National High School",
    "Batangas Province Science High School",
  ],
  "Balayan West": [
    "Balayan West Central School",
    "Caloocan Elementary School",
    "Agustin T. Ramos Memorial Elementary School",
    "Dilao Elementary School",
    "Doña Asuncion Martinez Memorial Elementary School",
    "Cepriana Ascue Memorial Elementary School",
    "Dr. Jose A. Alaras Elementary School",
    "Jose T. Unson Memorial Elementary School",
    "Jose Chua Ben Chong Memorial Elementary School",
    "Navotas Elementary School",
    "Flaviano-Pelagia Pantoja Memorial Elementary School",
    "Santol Elementary School",
    "Canda Integrated School",
    "San Piro National High School",
    "Balayan Senior High School",
    "Canda Integrated School",
  ],
  BALETE: [
    "Balete Central School",
    "Looc Elementary School",
    "Magapi Elementary School",
    "Cesar Oroña Elementary School",
    "Malabanan Elementary School",
    "Paligawan Elementary School",
    "Palsara Elementary School",
    "Solis Elementary School",
    "Emilia L. Malabanan Integrated School",
    "Balete National High School",
    "Primitivo Kalaw Senior High School",
    "Emilia L. Malabanan Integrated School",
  ],
  "Bauan East": [
    "Manghinao I Elementary School",
    "Alagao-Malindig Elementary School",
    "Bauan East Central School",
    "Manghinao Elementary School",
    "New Danglayan - Sto. Domingo Elementary School",
    "Pitugo Elementary School",
    "San Andres Elementary School",
    "San Roque Elementary School",
    "San Teodoro Elementary School",
    "Sinala Elementary School",
    "Sta. Maria - San Pedro Elementary School",
  ],
  "Bauan West": [
    "Baguilawa Elementary School",
    "Balayong Elementary School",
    "San Diego Elementary School",
    "West Bauan Central School",
    "Bolo Elementary School",
    "Centex Batangas",
    "Colvo Elementary School",
    "Cupang Elementary School",
    "Durungao Elementary School",
    "Inicbulan Elementary School",
    "Locloc Elementary School",
    "Manalupang - San Vicente Elementary School",
    "San Pablo Elementary School",
    "As-Is Integrated School",
    "Bauan National and Vocational Integrated High School",
    "Bauan Technical Integrated High School",
    "Inicbulan National High School",
    "San Vicente Manalupang National High School",
    "As-Is Integrated School",
  ],
  CALATAGAN: [
    "Balibago Elementary School",
    "Santiago Zobel Elementary School",
    "Jose M. Caisip Elementary School",
    "Bucal Elementary School",
    "Calambuyan Elementary School",
    "Jacobo Zobel Elementary School",
    "Carlosa Elementary School",
    "Carretonan Elementary School",
    "Encarnacion Elementary School",
    "Gulod Elementary School",
    "Hukay Elementary School",
    "Kilitisan Elementary School",
    "Paraiso Elementary School",
    "Angelita Zobel Elementary School",
    "Luya Elementary School",
    "Pedro Palacio Sr. Memorial Elementary School",
    "Pacita Madrigal Warns Mababang Paaralan ng Bagong Silang",
    "Enrique Zobel Elementary School",
    "Florencio D. Firmante Elementary School",
    "Talisay Elementary School",
    "Tanagan Elementary School",
    "Lucsuhin National High School",
    "CALATAGAN 2.0 NATIONAL HIGH SCHOOL",
    "Calatagan National High School",
    "Calatagan Senior High School",
  ],
  CUENCA: [
    "Balagbag Elementary School",
    "Briccio Pantas Memorial Elementary School",
    "Calumayin Elementary School",
    "Col. Pedro Pasia Memorial School",
    "Cuenca Central School",
    "Ramon Paterno Memorial Elementary School",
    "Dalipit East Bo. School",
    "Dalipit Elementary School",
    "Dr. Ananias Chavez Elementary School",
    "Emmanuel Elementary School",
    "Ibabao Elementary School",
    "Labac Elementary School",
    "Lumampao Elementary School",
    "San Felipe Elementary School",
    "Tomasa C. Pasia Memorial School",
    "Don Juan Integrated School",
    "Cuenca National High School",
    "Fermin La Rosa National High School",
    "Cuenca Senior High School",
    "Don Juan Integrated School",
  ],
  IBAAN: [
    "Balanga Elementary School",
    "Bungahan Elementary School",
    "Coliat Elementary School",
    "Gregorio Sison Memorial Elementary School",
    "Ibaan Central School",
    "Malainin Elementary School",
    "Panghayaan Elementary School",
    "Quilo Elementary School",
    "Sabang Elementary School",
    "Sto. Nino Elementary School",
    "Talaibon Elementary School",
    "Tulay Elementary School",
    "San Agustin Integrated School",
    "Procopio Mailig Memorial Integrated School",
    "Mabalor-Catandala Integrated School",
    "Lucsuhin Integrated School",
    "Dr. Juan A. Pastor Integrated National High School",
    "Maximo T. Hernandez Memorial Integrated High School",
    "San Agustin Integrated School",
    "Procopio Mailig Memorial Integrated School",
    "Mabalor-Catandala Integrated School",
    "Lucsuhin Integrated School",
  ],
  LAUREL: [
    "As-Is Elementary School",
    "Berinayan Elementary School",
    "Bignay Elementary School",
    "Buso-Buso Elementary School",
    "Gulod Elementary School",
    "Laurel Central School",
    "Leviste Elementary School",
    "Molinete Elementary School",
    "Niyugan Elementary School",
    "Paliparan Elementary School",
    "Pantay Elementary School",
    "San Gabriel Elementary School",
    "San Gregorio Elementary School - Annex",
    "Sta. Maria Elementary School",
    "Ticub Elementary School",
    "Martin Esperanza Elementary School",
    "San Gregorio Integrated School",
    "Bugaan Integrated School",
    "Balakilong Integrated School",
    "Wenceslao Trinidad Memorial National High School",
    "Placido T. Amo Senior High School",
    "San Gregorio Integrated School",
    "Bugaan Integrated School",
    "Balakilong Integrated School",
  ],
  LEMERY: [
    "Arumahan Elementary School",
    "Gulod Elementary School",
    "Marcos Catibog Memorial Elementary School",
    "Mayasang Elementary School",
    "R. Venturanza Central School",
    "Sambal Elementary School",
    "Sinisian Elementary School",
    "Talaga Elementary School",
    "Tubuan Elementary School",
    "V. Ornales Memorial Elementary School",
    "Ayao-Iyao Elementary School",
    "Bagong Paraiso Elementary School",
    "Bukal Elementary School",
    "Dayapan Elementary School",
    "Dita Elementary School",
    "Doña Matilde Memorial Elementray School",
    "Esteban E. Vito Memorial Elementary School",
    "Lemery Pilot Elementary School",
    "Mahayahay Elementary School",
    "Masalisi Elementary School",
    "Niogan Elementary School",
    "Payapa Elementary School",
    "Payapa Ibaba Elementary School",
    "San Isidro Itaas Elementary School",
    "San Isidro Labac Elementary School",
    "Payapa Senior High School",
    "Ananias C. Hernandez Memorial National High School",
    "Governor F. Leviste Memorial National High School",
    "Payapa National High School",
    "Lemery Senior High School",
    "Dionisio P. Vito National High School",
  ],
  LIAN: [
    "Bagong Pook Elementary School",
    "Balibago Elementary School",
    "Binubusan Elementary School",
    "Bungahan Elementary School",
    "Cumba Elementary School",
    "Humayingan Elementary School",
    "Kapito Elementary School",
    "Lian Central School",
    "Lumaniag Elementary School",
    "Luyahan Elementary School",
    "Matabungkay Elementary School",
    "Prenza Elementary School",
    "San Diego Elementary School",
    "Tanag Elementary School",
    "Putingkahoy Elementary School",
    "Malaruhatan Elementary School",
    "Matabungkay National High School",
    "Lian National High School",
    "Lian Senior High School",
  ],
  LOBO: [
    "Apar Elementary School",
    "Balatbat Elementary School",
    "Balibago Elementary School",
    "Banalo Elementary School",
    "Biga Elementary School",
    "Bignay Primary School",
    "Calo Elementary School",
    "Calumpit Elementary School",
    "Jaybanga Elementary School",
    "Lagadlarin/Olo-Olo Elementary School",
    "Lobo Central School",
    "Mabilog Na Bundok Elementary School",
    "Malabrigo Elementary School",
    "Malapad Na Parang Elementary School",
    "Masaguitsit Elementary School",
    "Nagtaluntong Elementary School",
    "Nagtoctoc Elementary School",
    "Pinaghawanan Elementary School",
    "Punas Elementary School",
    "San Miguel Elementary School",
    "San Nicolas Elementary School",
    "Sawang Elementary School",
    "Soloc Elementary School",
    "Jaybanga Integrated National High School",
    "Malabrigo National High School",
    "Malapad na Parang National High School",
    "Masaguitsit Banalo National High School",
    "Basilio S. Marasigan Memorial National High School",
    "Balibago-Biga National High School",
    "Lobo Senior High School",
  ],
  MABINI: [
    "Anilao Elementary School",
    "Bagalangit Elementary School",
    "Gasang Elementary School",
    "Laurel Elementary School",
    "Ligaya Primary School",
    "Mabini Central School",
    "Mainit Elementary School",
    "Malimatoc Elementary School",
    "Nag-iba Elementary School",
    "P. Anahao Elementary School",
    "Panay Elementary School",
    "San Jose Elementary School",
    "San Juan-Sto. Niño Elementary School",
    "San Teodoro Elementary School",
    "Solo Elementary School",
    "Sta. Mesa Elementary School",
    "Talaga Elementary School",
    "Mainaga-San Francisco Integrated School",
    "Anselmo A. Sandoval Memorial National High School",
    "Mabini National High School",
    "Apolinario Mabini National High School",
    "Mainaga-San Francisco Integrated School",
  ],
  MALVAR: [
    "Bagong Pook Elementary School",
    "Bilucao Elementary School",
    "Bulihan Elementary School",
    "Luta Elementary School",
    "Malvar Central School",
    "Miguel Aranda Memorial Elementary School",
    "Payapa Elementary School",
    "San Gregorio Elementary School",
    "San Isidro Elementary School",
    "San Juan Elementary School",
    "San Pedro Elementary School",
    "San Pioquinto Elementary School",
    "San Juan Sitio Balayan Elementary School",
    "Luta Norte Elementary School",
    "San Fernando Elementary School",
    "San Pedro I Integrated School",
    "Don Julio Leviste Memorial National High School",
    "Malvar School of Arts and Trade",
    "Luta Sur National High School",
    "San Isidro-Malvar Senior High School",
    "Santiago Malvar Senior High School",
    "San Isidro National High School (Malvar)",
    "Santiago National High School",
    "Malvar Senior High School",
    "San Pedro I Integrated School",
  ],
  MATAASNAKAHOY: [
    "Paaralang Elementarya ng Bayorbor",
    "Paaralang Elementarya ng Calingatan",
    "Paaralang Elementarya ng Kinalaglagan",
    "San Sebastian Elementary School",
    "Paaralang Elementarya Ng Loob",
    "Bubuyan Elementary School",
    "Paaralang Elementarya ng Lumanglipa",
    "Paaralang Sentral ng Mataasnakahoy",
    "Upa Primary School",
    "Paaralang Elementarya ng Nangkaan",
    "Santol - Manggahan Elementary School",
    "Bayorbor National High School",
    "Mataas na Kahoy National High School",
    "Mataasnakahoy Senior High School",
  ],
  "NASUGBU EAST": [
    "Aga Elementary School",
    "Paaralang Elementarya ng Banilad",
    "Bayabasan Elementary School",
    "Bilaran Elementary School",
    "Bulihan Elementary School",
    "Catandaan Elementary School",
    "Cogonan Elementary School",
    "Kaylaway Elementary School",
    "Kaylaway II Elementary School",
    "Kayrilaw Elementary School",
    "Latag Elementary School",
    "Looc Elementary School",
    "Malapad Na Bato Elementary School",
    "Mataas Na Pulo Elementary School",
    "Nasugbu East Central School",
    "Panuca Elementary School",
    "Pingkian Elementary School",
    "Tala Elementary School",
    "Tumalim Elementary School",
    "Banilad National High School",
    "Bilaran National High School",
    "Kaylaway National High School",
    "Looc National High School",
    "Lumbangan National High School",
    "Malapad na Bato National High School",
    "Tala National High School",
    "Tumalim National High School",
    "Catandaan Yabut National High School",
    "Tala Senior High School",
    "Nasugbu East Senior High School",
  ],
  "NASUGBU WEST": [
    "Balaytigue Elementary School",
    "Balokbalok Elementary School",
    "Bunducan Elementary School",
    "Calayo Elementary School",
    "Dayap Elementary School",
    "Maugat Elementary School",
    "Nasugbu West Central School",
    "Natipuan Elementary School",
    "Pantalan Elementary School",
    "Papaya Elementary School",
    "Utod Elementary School",
    "Wawa Elementary School",
    "Bucana Elementary School",
    "Dr. Crisogono B. Ermita, Sr. Memorial National High School",
    "Nasugbu National High School",
    "Balaytigue National High School",
    "Bunducan National High School",
    "Pantalan Senior High School",
  ],
  "PADRE GARCIA": [
    "Banaba Elementary School",
    "Paaralang Elementarya ng Banaybanay",
    "Bawi Elementary School",
    "Bukal Elementary School",
    "Castillo Elementary School",
    "Cawongan Elementary School",
    "Manggas-Tamak Elementary School",
    "Maugat East Elementary School",
    "Domingo M. Zuno Elementary School",
    "Padre Garcia Central School",
    "Pansol Elementary School",
    "Payapa Elementary School",
    "Anacleto Villanueva Elementary School",
    "Quilo-Quilo North Elementary School",
    "San Felipe Elementary School",
    "San Miguel Elementary School",
    "Tangob Elementary School",
    "Bukal Integrated National High School",
    "Padre Garcia Integrated National High School",
    "Pansol Integrated National High School",
  ],
  "ROSARIO EAST": [
    "Alupay Elementary School",
    "Bagong Pook Elementary School",
    "Balibago Elementary School",
    "Baybayin Elementary School",
    "Compradia Elementary School",
    "Mabato Elementary School",
    "Macalamcam Elementary School",
    "Malinao Elementary School",
    "Nasi Elementary School",
    "Natu Elementary School",
    "Palakpak Elementary School",
    "Putingkahoy Elementary School",
    "Rosario East Central School",
    "Salao East Elementary School",
    "Macalamcam B Elementary School",
    "San Carlos Elementary School",
    "San Isidro Elementary School",
    "Leon M. Manigbas Elementary School",
    "Tiquiwan Elementary School",
    "Maligaya Elementary School",
    "Pinagsibaan Integrated School",
    "Alupay Integrated National High School",
    "Baybayin Integrated National High School",
    "Macalamcam-B National High School",
    "Palakpak Integrated National High School",
    "The Saint Isidore National High School",
    "Rosario Technical High School",
    "Pinagsibaan Integrated School",
  ],
  "ROSARIO WEST": [
    "Antipolo Elementary School",
    "Bulihan Elementary School",
    "Cahigam Elementary School",
    "Calantas Elementary School",
    "Colongan Elementary School",
    "Itlugan Elementary School",
    "Julian D. Luna Elementary School",
    "Lumbangan Elementary School",
    "Paaralang Elementarya ng Maalas-as",
    "Paaralang Elementarya ng Mabunga",
    "Malaya Elementary School",
    "Marilag Elementary School",
    "Masaya Elementary School",
    "Mayuro Elementary School",
    "Namuco Elementary School",
    "Quilib - San Roque Elementary School",
    "Rosario West Central School",
    "San Ignacio Elementary School",
    "Tilaga Elementary School",
    "Paaralang Elementarya ng Timbugan",
    "Tubahan Elementary School",
    "Tulos Elementary School",
    "Mavalor Integrated School",
    "Bayawang Integated School",
    "Bulihan Integrated Senior High School",
    "Itlugan Integrated National High School",
    "Mayuro National High School",
    "Rosario Integrated National High School",
    "Timbugan National High School",
    "Tulos National High School",
    "Mayuro Senior High School",
    "Calantas National High School",
    "Calantas Senior High School",
    "Mavalor Integrated School",
    "Bayawang Integated School",
  ],
  "SAN JOSE": [
    "Banaybanay 1 Elementary School",
    "Aya Elementary School",
    "Bagong Pook Elementary School",
    "Balagtasin Elementary School",
    "Bigain Elementary School",
    "Benigna Dimatatac Memorial Elementary School",
    "Dagatan Elementary School",
    "Roman Ozaeta Memorial School",
    "Galamay-Amo Elementary School",
    "Lapolapo Elementary School",
    "Padre Imo Luna Memorial Elementary School",
    "Pinagtungulan Elementary School",
    "Salaban Elementary School",
    "Florencia A. Masilungan Memorial Elementary School",
    "Taysan Elementary School",
    "Tugtug Elementary School",
    "Marcos Espejo Integrated School",
    "Bigain Integrated School",
    "Taysan San Jose Integrated National High School",
    "Dr. Bonifacio A. Masilungan Integrated National High School",
    "Marcos Espejo Integrated School",
  ],
  "SAN JUAN EAST": [
    "Abung Elementary School",
    "Aplaya Elementary School",
    "Aplaya National High School",
    "Barualte Elementary School",
    "Bataan Elementary School",
    "Calitcalit Elementary School",
    "Calubcob I National High School",
    "Calubcub I Senior High School",
    "Calubcub II Elementary School",
    "Catmon Elementary School",
    "Coloconto Elementary School",
    "Hugom Elementary School",
    "Imelda Elementary School",
    "Laiya Elementary School",
    "Laiya Ibabao Elementary School",
    "Laiya Integrated National High School",
    "Libato Elementary School",
    "Lipahan National High School",
    "Lumangbayan Integrated National High School",
    "Nagsaulay Integrated National High School",
    "Paaralang Elementarya ng Calubcub 1",
    "Paaralang Elementarya ng Nagsaulay",
    "Paaralang Elementarya ng Poctol",
    "Paaralang Elementarya ng Talahiban 1.0",
    "Paaralang Elementarya ng Tipas",
    "Palingowak Elementary School",
    "Pinagbayanan Elementary School",
    "San Juan East Central School",
    "San Juan Senior High School",
    "Subukin Elementary School",
    "Talahiban II Elementary School",
    "Timoteo D. Aguila Elementary School",
    "Tipas Integrated National High School",
    "Wenceslao I. Llana Memorial School",
  ],
  "SAN JUAN WEST": [
    "Angeles Luistro Integrated Senior High School",
    "Balagbag Elementary School",
    "Buhaynasapa Integrated National High School",
    "Calabasahan Elementary School",
    "Don Eulogio Luistro Elementary School",
    "Don Leon Mercado, Sr. Memorial National High School",
    "Libato National High School",
    "Libjo Sapangan Elementary School",
    "Paaralang Elementarya ng Buhaynasapa",
    "Paaralang Elementarya ng Escribano",
    "Paaralang Elementarya Ng Janaojanao",
    "Paaralang Elementarya ng Mabalanoy",
    "Paaralang Elementarya ng Marcal",
    "Paaralang Elementarya ng Muzon",
    "Paaralang Elementarya ng Palahanan",
    "Paaralang Elementarya ng Pal-Sico",
    "Paaralang Elementarya ng Pulangbato",
    "Paaralang Elementarya ng Putingbuhangin",
    "Paaralang Elementarya ng Quipot",
    "Paaralang Elementarya ng Sampiro",
    "Pacita Ramos Mendoza Memorial National High School",
    "Palahanan Integrated National High School",
    "Pulangbato National High School",
    "Sampiro Integrated Senior High School",
    "San Juan West Central School",
    "Sapangan Elementary School",
    "Sico 1.0 Integrated National High School",
    "Ticalan Elementary School",
  ],
  "SAN LUIS": [
    "Abiacao Elementary School",
    "Balite Primary School",
    "Banoyo Elementary School",
    "Boboy Elementary School",
    "Bonliw Elementary School",
    "Calumpang East Elementary School",
    "Calumpang Elementary School",
    "Durungao Elementary School",
    "Locloc Elementary School",
    "Mahabang Parang Elementary School",
    "Muzon Elementary School",
    "San Antonio Elementary School",
    "San Luis Central School",
    "Sta. Monica Elementary School",
    "Taliba Elementary School",
    "Talon Elementary School",
    "Tungal Elementary School",
    "Luya Integrated School",
    "San Isidro Integrated School",
    "Sta.  Monica National High School",
    "Banoyo Integrated National High School",
    "San Luis Senior High School",
    "Luya Integrated School",
    "San Isidro Integrated School",
  ],
  "SAN NICOLAS": [
    "Abelo Elementary School",
    "Balete Elementary School",
    "Bancoro Elementary School",
    "Bangin Elementary School",
    "Calangay Elementary School",
    "Hipit Elementary School",
    "Maabud Elementary School",
    "Munlawin Elementary School",
    "San Nicolas Central School",
    "Sinturisan Elementary School",
    "Maabud Integrated National High School",
    "San Nicolas Integrated High School",
  ],
  "SAN PASCUAL": [
    "Balimbing Elementary School",
    "Alalum Elementary School",
    "Banaba Elementary School",
    "Bayanan Elementary School",
    "Gelerang Kawayan Elementary School",
    "Ilat Elementary School",
    "Kaingin Elementary School",
    "Laurel Elementary School",
    "Malakimpook Elementary School",
    "Mataas Na Lupa - Palsahingin Elementary School",
    "Natunuan North Elementary School",
    "Natunuan South Elementary School",
    "Pook Ng Kapitan Elementary School",
    "Pook Ni Banal Elementary School",
    "Resplandor Elementary School",
    "Sambat Elementary School",
    "San Antonio Elementary School",
    "San Mariano Elementary School",
    "San Pascual Central School",
    "Sto. Niño Elementary School",
    "Padre Castillo Elementary School",
    "Batangas Province High School Culture and Arts",
    "Alalum National High School",
    "Bayanan National High School",
    "Francisco G. Perez Memorial National High School",
    "Ilat National High School",
    "Malaking Pook National High School",
    "San Pascual National High School",
    "San Pascual Senior High School 1",
    "San Pascual Senior High School 2",
  ],
  "SANTA TERESITA": [
    "Burol Elementary School",
    "Calumala Elementary School",
    "Jorge M. Atienza Elementary School",
    "Irukan-Kalayaan Elementary School",
    "Mohon Elementary School",
    "Saimsim Elementary School",
    "Sta. Teresita Central School",
    "Sampa-Pacifico Integrated School",
    "Tambo Integrated School",
    "Sta. Teresita National High School",
    "Sampa-Pacifico Integrated School",
    "Tambo Integrated School",
  ],
  TAAL: [
    "Aguedo Lota Asinas Memorial Elementary School",
    "Balisong Elementary School",
    "Buli Elementary School",
    "Carmino Biscocho Memorial Elementary School",
    "Cultihan-Bolbok Elementary School",
    "Halang Elementary School",
    "Isabelo Baleros Memorial Elementary School",
    "Governor Vicente Noble Memorial Elementary School",
    "Latag Elementary School",
    "Luntal Elementary School",
    "Taal Central School",
    "Tulo Elementary School",
    "Antonio Bonsol Elementary School",
    "Cubamba Integrated School",
    "Apacay Integrated School",
    "Butong Integrated School",
    "Taal National High School",
    "Taal Senior High School",
    "Cubamba Integrated School",
    "Apacay Integrated School",
    "Butong Integrated School",
  ],
  TALISAY: [
    "Venancio Trinidad Sr. Memorial School",
    "Balas Elementary School",
    "Banga Elementary School",
    "Caloocan Elementary School",
    "Doña Maria Laurel Platon Memorial School",
    "Jorge B. Vargas Memorial Elementary School",
    "Miranda Elementary School",
    "Quiling Elementary School",
    "Tranca Elementary School",
    "San Guillermo Elementary School",
    "Balas Buco Sta. Maria National High School",
    "Dona Maria Laurel Platon School of Agriculture",
    "Talisay Senior High School",
  ],
  TAYSAN: [
    "Bilogo Elementary School",
    "Bucal Elementary School",
    "Dagatan Elementary School",
    "Paaralang Elementarya ng Laurel",
    "Mapulo Elementary School",
    "Pag-asa Elementary School",
    "Panghayaan Elementary School",
    "Piña Elementary School",
    "Bacao Elementary School",
    "Pinagbayanan Elementary School",
    "Paaralang Elementarya ng San Isidro",
    "San Marcelino Elementary School",
    "Guinhawa Elementary School",
    "Sto. Nino Elementary School",
    "Conde Elementary School",
    "Taysan Central School",
    "Mabayabas Elementary School",
    "Mataas na Lupa Elementary School",
    "Tilambo Elementary School",
    "Bilogo Integrated National High School",
    "Dagatan Integrated National High School",
    "Pinagbayanan Integrated National High School",
    "San Isidro National High School",
    "Tilambo National High School",
    "Mahanadiong National High School",
    "Taysan Senior High School",
  ],
  TINGLOY: [
    "Banalo Elementary School",
    "Corona Elementary School",
    "Gamaw Elementary School",
    "Makawayan Elementary School",
    "Marikaban Elementary School",
    "Papaya Elementary School",
    "Pisa Elementary School",
    "San Jose Elementary School",
    "San Juan Elementary School",
    "San Pedro Elementary School",
    "Sto. Tomas Elementary School",
    "Talahib Elementary School",
    "Bago Primary School",
    "Tingloy Central School",
    "Papaya National High School",
    "Tingloy National High School",
    "Tingloy Senior High School",
  ],
  TUY: [
    "Bayudbud Elementary School",
    "Bolbok Elementary School",
    "Dalima Elementary School",
    "Dao Elementary School",
    "Gregorio Agoncillo Elementary School",
    "Gregorio Paradero Elementary School",
    "Guinhawa Elementary School",
    "Gumapac Barangay School",
    "Jose Zabarte Elementary School",
    "Lumbangan-Talon Elementary School",
    "Luntal Elementary School",
    "Magahis Elementary School",
    "Mataywanak Elementary School",
    "Julian Castillo Memorial Elementary School",
    "Eulogio G. Cerrado Elementary School",
    "San Jose Elementary School",
    "Santiago De Guzman Elementary School",
    "Toong Elementary School",
    "Bolbok National High School",
    "Maria Paz Fronda National High School",
    "Jose Lopez Manzano National High School",
    "Tuy National High School",
    "Tuy Senior High School",
  ],
};

/** All schools flattened (for search / fallback). */
export const ALL_SCHOOLS: string[] = Object.values(SCHOOLS_BY_SUB_OFFICE).flat();

/**
 * Look up the sub-office for a given school name.
 * Returns undefined if the school is not found.
 */
export function findSubOfficeForSchool(school: string): string | undefined {
  for (const [sub, schools] of Object.entries(SCHOOLS_BY_SUB_OFFICE)) {
    if (schools.includes(school)) return sub;
  }
  return undefined;
}
